public class Array{
    public static void main(String[] args){
        
        int num[] = new int[4];
         num[0] = 1;
         num[2]=3;
         num[1]=4;
         num[3]=9;
        for(int i=0; i<4; i++)
        {
            System.out.println(num[i]);
        }

        // Reverse the content

        // char num[] = {'s', 'u', 'd', 'e', 'e', 'p'};
        // for (int i = 5; i >= 0; i--) {
        //     System.out.println(num[i]);
        // }
    }
}